# 必选 版本号，例如v1
apiVersion: v1
# 必选 Pod
kind: Pod
# 必选 元数据
metadata:
  # pod的名称
  name: string
  # pod所属命名空间
  namespace: string
  # 自定义标签列表 array
  labels:
    - name: string
  # 自定义注解列表 array
  annotations:
    - name: string
# 容器的详细定义
spec:
  # pod 中容器的详细定义
  containers:
    # 容器名称
  - name: string
    # 容器镜像名称
    image: string
    imagePullPolicy: [Always | Never | IfNotPresent]
    command: [string]
    args: [string]
    workingDir: string
    volumeMounts:
    - name: string
      mountPath: string
      readOnly: boolean
    ports:
    - name: string
      containerPort: int
      hostPort: int
      protocol: string
    env:
    - name: string
      value: string
resources:
  limits:
    cpu: string
    memory: string
  requests:
    cpu: string
    memory: string
livenessProbe:
  exec:
    command: [string]
  httpGet:
    path: string
    port: number
    host: string
    scheme: string
    httpHeaders:
    - name: string
      value: string
  tcpSocket:
    port: number
  initialDelaySeconds: 0
  timeoutSeconds: 0
  periodSeconds: 0
  successThreshold: 0
  failureThreshold: 0
securityContext:
  privileged: false
restartPolicy: [Always | Never | OnFailure]
nodeSelector: object
imagePullSecrets:
  - name: string
hostNetwork: false
volumes:
- name: string
  emptyDir: {}
  hostPath:
    path: string
  secret:
    secretName: string
    items:
    - key: string
      path: string
    configMap:
      name: string
      items:
      - key: string
        path: string